services:
  auth-service:
    volumes:
      - ./services/auth:/app
      - auth-node-modules:/app/node_modules
    environment:
      - NODE_ENV=development
    command: ["/app/entrypoint.sh"]

  web-app:
    volumes:
      - ./apps/web_app:/app
      - web-app-node-modules:/app/node_modules
    environment:
      - NODE_ENV=development
    command: ["/app/entrypoint.sh"]

  tasks-service:
    volumes:
      - ./services/tasks:/app
      - tasks-node-modules:/app/node_modules
    environment:
      - NODE_ENV=development
    command: ["/app/entrypoint.sh"]

  notification-service:
    volumes:
      - ./services/notifications:/app
      - notification-node-modules:/app/node_modules
    environment:
      - NODE_ENV=development
    command: ["/app/entrypoint.sh"]

  nginx:
    volumes:
      - ./infrastructure/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./infrastructure/nginx/conf.d:/etc/nginx/conf.d:ro

volumes:
  web-app-node-modules:
  auth-node-modules:
  tasks-node-modules:
  notification-node-modules: