services:
  auth-service:
    volumes:
      - ./services/auth:/app:cached
      - auth-node-modules:/app/node_modules
    environment:
      - NODE_ENV=development
    command: >
      sh -c "
        until nc -z auth-database 3306; do
          echo 'Waiting for auth-database...'; sleep 1;
        done &&
        npx prisma generate &&
        npx prisma migrate deploy &&
        npm run dev
      "

  web-app:
    volumes:
      - ./apps/web_app:/app:cached
      - web-app-node-modules:/app/node_modules
    environment:
      - NODE_ENV=development

  tasks-service:
    volumes:
      - ./services/tasks:/app:cached
      - tasks-node-modules:/app/node_modules
    environment:
      - NODE_ENV=development
    command: >
      sh -c "
        until nc -z tasks-database 3306; do
          echo 'Waiting for tasks-database...'; sleep 1;
        done &&
        npx prisma generate &&
        npx prisma migrate deploy &&
        npm run dev
      "

  api-gateway:
    volumes:
      - ./api-gateway/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./api-gateway/conf.d:/etc/nginx/conf.d:ro

volumes:
  web-app-node-modules:
  auth-node-modules:
  tasks-node-modules: