_format_version: "3.0"

consumers:
  - username: auth-client
    custom_id: auth-client-id
    jwt_secrets:
      - algorithm: RS256
        key: auth-client
        secret: fake-jwt-secret         # Kong does not use this field for RS256, but it is required for the configuration to be valid.
        rsa_public_key: |
          -----BEGIN PUBLIC KEY-----
          MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEA2t4JS/5aMxvPQMonb4q0
          EDH6GcomySzBbowZ9OuTKBnuf51NgCI12xNMpEhqrm+d1VsEw0MaoDqFyvpXhFWk
          KHQhjlxrHPX5MyuLyS7sx5ERmPw2bPgX036qfVY9xyMpgiQbVWLD8rTKijT0Tg9H
          5iTZ5WRMeKvdZn9svQGqMS++VPl0zKW3xhJIiwdiOkQFcp23sinAAdsGI+O1eKCz
          ZfjvU0VhKvwvWTiG5RtnzexyaBYifoD10LgBEOw29XjDBHHpV5EkczmRiiLkMnqs
          mPNYfsENXqaj/JAPP1rbhMADRUHCx6NkZbaBV7FHVbbQX7oYNn/FgIuwHlTlyvqq
          RQIDAQAB
          -----END PUBLIC KEY-----

upstreams:
  - name: auth-service-upstream
    targets:
      - target: auth-service:1111
  - name: tasks-service-upstream
    targets:
      - target: tasks-service:2222
  - name: suggestions-service-upstream
    targets:
      - target: suggestions-service:4444

services:
  - name: auth-service
    host: auth-service-upstream
    port: 1111
    protocol: http
    routes:
      - name: auth-public
        strip_path: false
        paths:
          - /api/auth/login
          - /api/auth/register
          - /api/auth/verification/resend
          - /api/auth/verification
          - /api/auth/forgot-password
          - /api/auth/reset-password/verify-code
          - /api/auth/reset-password
          - /api/users

      - name: auth-protected
        strip_path: false
        paths:
          - /api/users/me
          - /api/auth/logout
        plugins:
          - name: jwt
          - name: jwt-payload-header

  - name: tasks-service
    host: tasks-service-upstream
    port: 2222
    protocol: http
    routes:
      - name: tasks-route
        strip_path: false
        paths:
          - /api/tasks
        plugins:
          - name: jwt
          - name: jwt-payload-header

  - name: suggestions-service
    host: suggestions-service-upstream
    port: 4444
    protocol: http
    routes:
      - name: suggestions-route
        strip_path: false
        paths:
          - /api/suggestions
