name: Auth Service CI

on:
  push:
    paths:
      - 'services/auth/**'
  pull_request:
    paths:
      - 'services/auth/**'

jobs:
  test-auth:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: services/auth

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install

      - name: Run tests
        run: npm test
